# Generated by Django 5.1.1 on 2026-05-05 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('bank', 'Bank Transfer')], default='mpesa', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('credited', 'Credited to Wallet'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('reference', models.CharField(blank=True, db_index=True, help_text='M-Pesa receipt, bank ref, or manual note', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='For M-Pesa STK deposits', max_length=15)),
                ('proof_file', models.FileField(blank=True, help_text='Receipt image or bank slip (optional)', null=True, upload_to='deposit_proofs/')),
                ('notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_deposits', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'status'], name='wallets_dep_wallet__5ffd15_idx'), models.Index(fields=['reference'], name='wallets_dep_referen_ccb9cd_idx')],
            },
        ),
    ]
