# Generated by Django 5.1.1 on 2026-05-10 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamapro', '0007_subscriptionpayment_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='chama',
            name='late_penalty',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AddField(
            model_name='chama',
            name='loan_interest',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='chama',
            name='max_members',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='chama',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ChamaBillingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Pro')], max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mpesa_ref', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_payments', to='chamapro.chama')),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chama_billing_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChamaNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_contribution_due', models.BooleanField(default=True)),
                ('notif_contribution_received', models.BooleanField(default=True)),
                ('notif_contribution_overdue', models.BooleanField(default=True)),
                ('notif_fine_issued', models.BooleanField(default=False)),
                ('reminder_days_before', models.PositiveSmallIntegerField(default=3)),
                ('notif_loan_requested', models.BooleanField(default=True)),
                ('notif_loan_approved', models.BooleanField(default=True)),
                ('notif_loan_rejected', models.BooleanField(default=True)),
                ('notif_loan_repayment', models.BooleanField(default=False)),
                ('notif_withdrawal_requested', models.BooleanField(default=True)),
                ('notif_member_joined', models.BooleanField(default=True)),
                ('notif_member_left', models.BooleanField(default=True)),
                ('notif_role_changed', models.BooleanField(default=False)),
                ('channel_in_app', models.BooleanField(default=True)),
                ('channel_email', models.BooleanField(default=True)),
                ('channel_sms', models.BooleanField(default=False)),
                ('from_email', models.EmailField(default='noreply@chamapro.app', max_length=254)),
                ('sms_sender', models.CharField(default='ChamaPro', max_length=11)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chama', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='chamapro.chama')),
            ],
        ),
    ]
