# Generated by Django 5.1.1 on 2026-05-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamapro', '0008_chama_late_penalty_chama_loan_interest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_type', models.CharField(choices=[('financial', 'Financial institution'), ('sacco', 'Sacco'), ('ngo', 'NGO'), ('tech', 'Technology company'), ('consultant', 'Consultant'), ('other', 'Other')], max_length=20)),
                ('org_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=30)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('offering', models.CharField(choices=[('referrals', 'Client referrals'), ('reselling', 'Distribution / reselling'), ('integration', 'Technical integration'), ('comarketing', 'Co-marketing'), ('other', 'Other')], max_length=20)),
                ('expectations', models.TextField(blank=True)),
                ('scale', models.CharField(blank=True, choices=[('1-50', '1 – 50'), ('51-200', '51 – 200'), ('201-1000', '201 – 1,000'), ('1000+', '1,000+')], max_length=20)),
                ('agreed_terms', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
            ],
            options={
                'verbose_name': 'Partner application',
                'verbose_name_plural': 'Partner applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
